version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: slotify_backend_development
      POSTGRES_USER: slotify_backend
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U slotify_backend -d slotify_backend_development"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./slotify_backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://slotify_backend:password@db:5432/slotify_backend_development
    volumes:
      - ./slotify_backend:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        bundle install &&
        bundle exec rails db:create db:migrate db:seed &&
        bundle exec rails server
      "

  frontend:
    build:
      context: ./slotify_frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./slotify_frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend

volumes:
  postgres_data:
  bundle_cache:
